# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-06-18 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_to_image', models.CharField(max_length=25000)),
                ('update', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='shop.Base')),
                ('title', models.CharField(max_length=250)),
                ('product_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('processor', models.CharField(max_length=200)),
                ('video_card', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('resolution', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True)),
                ('weight', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, max_length=250, primary_key=True, serialize=False, unique=True)),
            ],
            bases=('shop.base',),
        ),
        migrations.AddField(
            model_name='base',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
